# Site settings
source:          .
destination:     ./staging

title: Das Keyboard
email: camille@metadot.com
email_name: camille@
baseurl: "/q-website" # the subpath of your site, e.g. /blog/
url: "https://daskeyboard.github.io"
github_username: DasKeyboard

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

exclude: [example, packages, tool]