# Site settings
source:          .
destination:     ./_site

title: Das Keyboard
email: support@metadot.com
email_name: support@
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.daskeyboard.io"
github_username: DasKeyboard

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

exclude: [packages, tool]
